#!/bin/sh
set -eux

ROOTDIR=$(cd "$(dirname "$0")" && pwd)

"$ROOTDIR/tools/check_readme.sh"
cargo audit
cargo fmt
cargo clippy
cargo test
cargo doc
cargo run --no-default-features --example no_std_demo
cargo run --example demo
